# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode12.5
language: swift
script: xcodebuild clean build test -workspace Example/QBIndicatorButton.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
